### ISSUE TITLE
处于“未执行”状态的任务如何关闭？ | 作者回复：已修复，这个也是adb版本问题导致的没有直接执行。

### ISSUE THREAD

**Issue by TimeLine61** [1033866383/perf-orange-cat#1]

**Comment by 1033866383** [comment]
1.任务一创建就会执行，未执行应该是你这个手机的连接是断开的。
2.具体api访问：http://localhost/redoc  这里的 /delete 接口是删除。
3.针对这个问题我会修改一下重新发包

**Comment by TimeLine61** [comment]
> 1.任务一创建就会执行，未执行应该是你这个手机的连接是断开的。 2.具体api访问：http://localhost/redoc 这里的 /delete 接口是删除。 3.针对这个问题我会修改一下重新发包

不是啊，手机一直是连着的，我访问了localhost/delete_task/接口，返回{"detail":[{"loc":["query","id"],"msg":"field required","type":"value_error.missing"}]}，还是无法删除任务

**Comment by TimeLine61** [comment]
而且也无法再开启任务，死局........烦请尽快修改一下，很不错的项目，支持

**Comment by 1033866383** [comment]
已经改了，一会打包发。delete需要带id的，或者简单粗暴你把可执行文件，旁边的 task.sqlite 直接删除，那个是数据库。你把他删了就可以重新开始建任务了。
你反馈的这个我再查查看看能不能复现

**Comment by TimeLine61** [comment]
> 已经改了，一会打包发。delete需要带id的，或者简单粗暴你把可执行文件，旁边的 task.sqlite 直接删除，那个是数据库。你把他删了就可以重新开始建任务了。 你反馈的这个我再查查看看能不能复现

我用的是android真机，换另一台真机选择好设备和app包之后，哪怕显示“创建任务成功”提示了，但任务状态总是“未执行”

**Comment by 1033866383** [comment]
问题已经查到了，是有一个adb进程未结束，它会导致新的adb进程获取数据时提示 连接失败，已经修复了，具体你可以在log.log 中看倒 adb 的err stdout

**Comment by 1033866383** [comment]
你好，android 启动状态为未执行的问题已经解决了，并且后续为了维护，我把包发送在了 pypi 上。
安装：pip install performancetest
启动：python -m performancetest.web.main
启动后访问：http://localhost/ 即可

> > 已经改了，一会打包发。delete需要带id的，或者简单粗暴你把可执行文件，旁边的 task.sqlite 直接删除，那个是数据库。你把他删了就可以重新开始建任务了。 你反馈的这个我再查查看看能不能复现
> 
> 我用的是android真机，换另一台真机选择好设备和app包之后，哪怕显示“创建任务成功”提示了，但任务状态总是“未执行”
