### ISSUE TITLE
遊戲類型的apk  數據除了FPS以外都可以正常擷取，想請問一下有什麼可能的原因導致FPS數據擷取不到

### ISSUE THREAD

**Issue by marrash** [1033866383/perf-orange-cat#10]

**Comment by 1033866383** [comment]
这个个项目是专门针对游戏项目做的。我本人也是游戏公司的成员，工作方向也是针对游戏做移动端性能。所以应该是可以拿到fps，方便提供下日志吗

**Comment by 1033866383** [comment]
> _No description provided._

这个项目是专门针对游戏项目做的。我本人也是游戏公司的成员，工作方向也是针对游戏做移动端性能。所以应该是可以拿到fps，方便提供下日志吗

**Comment by 1033866383** [comment]
> _No description provided._

或者把你的app给我我测试一下

**Comment by wangzhangjun** [comment]
播放视频时拿不到fps和掉帧。看了作者的实现是基于dumpsys surfaceflinger --latency， 这个命令很多时候全是0，比如--latency-clear之后，一直获取不到。暂时不知道原因。

**Comment by 1033866383** [comment]
> 播放视频时拿不到fps和掉帧。看了作者的实现是基于dumpsys surfaceflinger --latency， 这个命令很多时候全是0，比如--latency-clear之后，一直获取不到。暂时不知道原因。

我看抖音是可以都拿到帧率的 你这个视频指的是 爱奇艺之类是吗

**Comment by wangzhangjun** [comment]
> > 播放视频时拿不到fps和掉帧。看了作者的实现是基于dumpsys surfaceflinger --latency， 这个命令很多时候全是0，比如--latency-clear之后，一直获取不到。暂时不知道原因。
> 
> 我看抖音是可以都拿到帧率的 你这个视频指的是 爱奇艺之类是吗

用B 站测的。 还有个问题请教下作者，为啥我用adb 命令看dumpsys surfaceflinger --latency， 经常是0 ，即使是手机正在播放视频，按理来说这个时候是有数据的，因为我看原理这个命令是数据的来源。

**Comment by 1033866383** [comment]
增加了 gfxinfo 获取不到fps应该是解决了
