### ISSUE TITLE
获取系统cpu最大值超过了100？？？

### ISSUE THREAD

**Issue by chimianshaonian** [1033866383/perf-orange-cat#13]
![image](https://github.com/1033866383/perf-orange-cat/assets/73635546/b95ffd7b-8c01-447f-92f2-7d13f7735338)

**Comment by 1033866383** [comment]
> ![image](https://user-images.githubusercontent.com/73635546/277632082-b95ffd7b-8c01-447f-92f2-7d13f7735338.png)

这个算的系统总值，proc-stat  拿的但是一个时间端 1s以内的值 所以100左右都是正常的

**Comment by 1033866383** [comment]
所以无论是 top 获取cpu， 还是proc-stat 获取cpu都是一个时间段也就是1s的值。

**Comment by chimianshaonian** [comment]
好的，我再试下，谢谢
