### ISSUE TITLE
额，没有源码？

### ISSUE THREAD

**Issue by GlodenBoy** [1033866383/perf-orange-cat#4]
![image](https://github.com/1033866383/perf-orange-cat/assets/2329528/d154890c-83ad-48a2-96f2-737487472962)

**Comment by 1033866383** [comment]
用pip 装的啊，源码已经在你本地了

**Comment by 1033866383** [comment]
> ![image](https://user-images.githubusercontent.com/2329528/252254836-d154890c-83ad-48a2-96f2-737487472962.png)

用pip 装的啊，源码已经在你本地了
为了防止找不到，源码提价到github了

**Comment by 1033866383** [comment]
> ![image](https://user-images.githubusercontent.com/2329528/252254836-d154890c-83ad-48a2-96f2-737487472962.png)

用了记得star哦
