### ISSUE TITLE
支持无线模式，连接IOS设备吗？ | 作者回复：ios 暂时没法支持无线

### ISSUE THREAD

**Issue by haojunwei-hub** [1033866383/perf-orange-cat#7]
电量只有百分比，没有具体电压、电流，无法评估功耗，且usb连接情况下，影响放电的准确性，对电流这一块，大佬后续有规划吗

**Comment by 1033866383** [comment]
ios 无线模式应该是不行，即便是做成sdk应该也不能无线。  具体功耗，ios性能是用的instrumentsserver，后面我有时间可以研究一下这个服务有没有这个指标
