### ISSUE TITLE
获取不到应用list | 作者回复：这个没拿到是因为检测到设备后没有选中设备，认真看下面的教程谢谢。

### ISSUE THREAD

**Issue by haojunwei-hub** [1033866383/perf-orange-cat#8]
![image](https://github.com/1033866383/perf-orange-cat/assets/54835391/a76f455e-e13f-42a5-9178-a5937ec5fcd7)

![image](https://github.com/1033866383/perf-orange-cat/assets/54835391/7a14aec9-91d1-48b0-8b9c-24a81acda28b)
也没看到接口报错，
设备：13ProMax 15.6.1

**Comment by 1033866383** [comment]
> ![image](https://user-images.githubusercontent.com/54835391/254797319-a76f455e-e13f-42a5-9178-a5937ec5fcd7.png)
> 
> ![image](https://user-images.githubusercontent.com/54835391/254797437-7a14aec9-91d1-48b0-8b9c-24a81acda28b.png) 也没看到接口报错， 设备：13ProMax 15.6.1

上面的设备的那个单选框，请选中它。
![image](https://github.com/1033866383/perf-orange-cat/assets/56209295/34a95983-d3b3-476c-8e92-da1d71522f07)
